language: node_js
node_js: stable

install:
  - npm install hexo

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "SeanDragon"
  - git config user.email "syl8023who@gmail.com"
  - git add .
  - git commit -a -m "自动构建hexo分支的博客代码"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo

env:
 global:
   - GH_REF: github.com/SeanDragon/SeanDragon.github.io.git
