name: 自动化编译并发布博客内容
on:
  push:
    branches: [ hexo ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载
        uses: actions/checkout@v2
        with:
          ref: hexo
      - name: 设置NodeJS环境
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: 设置hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "SeanDragon"
          git config --global user.email "syl8023who@gmail.com"
          npm install hexo-cli -g
          npm install
      - name: 部署hexo
        run: |
          hexo clean
          hexo generate
          hexo deploy
