# This is a basic workflow to help you get started with Actions

name: 自动化编译并发布博客内容

env:
  GH_REF: git@github.com:SeanDragon/SeanDragon.github.io.git

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the hexo branch
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - run: npm install
      - run: npm run clean
      - run: npm run build
      - run: |
          cd ./public
          git init
          git add .
          git commit -a -m "自动构建hexo分支的博客代码"
          git push --force --quiet "${GH_REF}" master:master
